package pokecompare

val typeCoefs: Map[MoveType, Map[PokeType, Double]] =
  Map( //                       bug   dar   dra   ele   fai   fig   fir   fly   gho   gra   gro   ice   nor   poi   psy   roc   ste   wat   non
    MoveType.Bug ->      List( 1.00, 1.25, 1.00, 1.00,  .80,  .80,  .80,  .80,  .80, 1.25, 1.00, 1.00, 1.00,  .80, 1.25, 1.00,  .80, 1.00, 1.00),
    MoveType.Dark ->     List( 1.00,  .80, 1.00, 1.00,  .80,  .80, 1.00, 1.00, 1.25, 1.00, 1.00, 1.00, 1.00, 1.00, 1.25, 1.00, 1.00, 1.00, 1.00), 
    MoveType.Dragon ->   List( 1.00, 1.00, 1.25, 1.00,  .80, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00,  .80, 1.00, 1.00),
    MoveType.Electric -> List( 1.00, 1.00,  .80,  .80, 1.00, 1.00, 1.00, 1.25, 1.00,  .80,  .80, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.25, 1.00),
    MoveType.Fairy ->    List( 1.00, 1.25, 1.25, 1.00, 1.00, 1.25,  .80, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00,  .80, 1.00, 1.00,  .80, 1.00, 1.00),
    MoveType.Fighter ->  List(  .80, 1.25, 1.00, 1.00,  .80, 1.00, 1.00,  .80,  .80, 1.00, 1.00, 1.25, 1.25,  .80,  .80, 1.25, 1.25, 1.00, 1.00),
    MoveType.Fire ->     List( 1.25, 1.00,  .80, 1.00, 1.00, 1.00,  .80, 1.00, 1.00, 1.25, 1.00, 1.25, 1.00, 1.00, 1.00,  .80, 1.25,  .80, 1.00),
    MoveType.Flying ->   List( 1.25, 1.00, 1.00,  .80, 1.00, 1.25, 1.00, 1.00, 1.00, 1.25, 1.00, 1.00, 1.00, 1.00, 1.00,  .80,  .80, 1.00, 1.00),
    MoveType.Ghost ->    List( 1.00,  .80, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.25, 1.00, 1.00, 1.00,  .80, 1.00, 1.25, 1.00, 1.00, 1.00, 1.00),
    MoveType.Grass ->    List(  .80, 1.00,  .80, 1.00, 1.00, 1.00,  .80,  .80, 1.00,  .80, 1.25, 1.00, 1.00,  .80, 1.00, 1.25,  .80, 1.25, 1.00),
    MoveType.Ground ->   List(  .80, 1.00, 1.00, 1.25, 1.00, 1.00, 1.25,  .80, 1.00,  .80, 1.00, 1.00, 1.00, 1.25, 1.00, 1.25, 1.25, 1.00, 1.00),
    MoveType.Ice ->      List( 1.00, 1.00, 1.25, 1.00, 1.00, 1.00,  .80, 1.25, 1.00, 1.25, 1.25,  .80, 1.00, 1.00, 1.00, 1.00,  .80,  .80, 1.00),
    MoveType.Normal ->   List( 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00,  .80, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00,  .80,  .80, 1.00, 1.00),
    MoveType.Poison ->   List( 1.00, 1.00, 1.00, 1.00, 1.25, 1.00, 1.00, 1.00,  .80, 1.25,  .80, 1.00, 1.00,  .80, 1.00,  .80,  .80, 1.00, 1.00),
    MoveType.Psychic ->  List( 1.00,  .80, 1.00, 1.00, 1.00, 1.25, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.25,  .80, 1.00,  .80, 1.00, 1.00),
    MoveType.Rock ->     List( 1.25, 1.00, 1.00, 1.00, 1.00,  .80, 1.25, 1.25, 1.00, 1.00,  .80, 1.25, 1.00, 1.00, 1.00, 1.00,  .80, 1.00, 1.00),
    MoveType.Steel ->    List( 1.00, 1.00, 1.00,  .80, 1.25, 1.00,  .80, 1.00, 1.00, 1.00, 1.00, 1.25, 1.00, 1.00, 1.00, 1.25,  .80,  .80, 1.00),
    MoveType.Water ->    List( 1.00, 1.00,  .80, 1.00, 1.00, 1.00, 1.25, 1.00, 1.00,  .80, 1.25, 1.00, 1.00, 1.00, 1.00, 1.25, 1.00,  .80, 1.00),
  ).view.mapValues(_.zip(PokeType.values).map(_.swap).toMap).toMap

trait Move(val mType: MoveType, val damage: Int, val time: Double, val energy: Int)

enum FastMove(mt: MoveType, d: Int, t: Double, e: Int) extends Move(mt, d, t, e):
  //                                              type     damage  time energy
  case Acid             extends FastMove(MoveType.Poison,      10, 1.05,    7)
  case Bite             extends FastMove(MoveType.Dark,         6,  .50,    7)
  case Bubble           extends FastMove(MoveType.Water,       25, 2.30,   15)
  case BugBite          extends FastMove(MoveType.Bug,          5, 0.45,    7)
  case BulletPunch      extends FastMove(MoveType.Steel,       10, 1.20,    7)
  case Confusion        extends FastMove(MoveType.Psychic,     15, 1.51,    7)
  case DragonBreath     extends FastMove(MoveType.Dragon,       6, 0.50,    7)
  case Ember            extends FastMove(MoveType.Fire,        10, 1.05,    7)
  case FeintAttack      extends FastMove(MoveType.Dark,        12, 1.04,    7)
  case FireFang         extends FastMove(MoveType.Fire,        10, 0.84,    4)
  case FrostBreath      extends FastMove(MoveType.Ice,          9, 0.81,    7)
  case FuryCutter       extends FastMove(MoveType.Bug,          3, 0.40,   12)
  case IceShard         extends FastMove(MoveType.Ice,         15, 1.40,    7)
  case KarateChop       extends FastMove(MoveType.Fighter,      6, 0.80,    7)
  case Lick             extends FastMove(MoveType.Ghost,        5, 0.50,    7)
  case LowKick          extends FastMove(MoveType.Fighter,      5, 0.60,    7)
  case MetalClaw        extends FastMove(MoveType.Steel,        8, 0.63,    7)
  case MudShot          extends FastMove(MoveType.Ground,       6, 0.55,    7)
  case MudSlap          extends FastMove(MoveType.Ground,      15, 1.35,    9)
  case Peck             extends FastMove(MoveType.Flying,      10, 1.15,   10)
  case PoisonJab        extends FastMove(MoveType.Poison,      12, 1.05,    7)
  case PoisonSting      extends FastMove(MoveType.Poison,       6, 0.58,    4)
  case Pound            extends FastMove(MoveType.Normal,       7, 0.54,    7)
  case PsychoCut        extends FastMove(MoveType.Psychic,      7, 0.57,    7)
  case QuickAttack      extends FastMove(MoveType.Normal,      10, 1.33,    7)
  case RazorLeaf        extends FastMove(MoveType.Grass,       15, 1.45,    7)
  case RockSmash        extends FastMove(MoveType.Fighter,     15, 1.41,    7)
  case RockThrow        extends FastMove(MoveType.Rock,        12, 1.36,    7)
  case Scratch          extends FastMove(MoveType.Normal,       6, 0.50,    7)
  case ShadowClaw       extends FastMove(MoveType.Ghost,       11, 0.95,    7)
  case Spark            extends FastMove(MoveType.Electric,     7, 0.79,    4)
  case Splash           extends FastMove(MoveType.Water,        0, 1.23,    7)
  case SteelWing        extends FastMove(MoveType.Steel,       15, 1.33,    4)
  case SuckerPunch      extends FastMove(MoveType.Dark,         7, 0.79,    4)
  case Tackle           extends FastMove(MoveType.Normal,      12, 1.19,    7)
  case ThunderShock     extends FastMove(MoveType.Electric,     5, 0.69,    7)
  case VineWhip         extends FastMove(MoveType.Grass,        7, 0.65,    7)
  case WaterGun         extends FastMove(MoveType.Water,        6, 0.59,    7)
  case WingAttack       extends FastMove(MoveType.Flying,       9, 0.75,    7)
  case ZenHeadbutt      extends FastMove(MoveType.Psychic,     12, 1.05,    4)

enum ChargeMove(mt: MoveType, d: Int, t: Double, e: Int) extends Move(mt, d, t, e):
  //                                              type     damage  time energy
  case AerialAce      extends ChargeMove(MoveType.Flying,      30, 2.90,  -25)
  case AirCutter      extends ChargeMove(MoveType.Flying,      30, 3.30,  -25)
  case AncientPower   extends ChargeMove(MoveType.Rock,        35, 3.60,  -25)
  case AquaJet        extends ChargeMove(MoveType.Water,       25, 2.35,  -20)
  case AquaTail       extends ChargeMove(MoveType.Water,       45, 2.35,  -50)
  case Blizzard       extends ChargeMove(MoveType.Ice,        100, 3.90, -100)
  case BodySlam       extends ChargeMove(MoveType.Normal,      40, 1.56,  -50)
  case BoneClub       extends ChargeMove(MoveType.Ground,      25, 1.60,  -25)
  case BrickBreak     extends ChargeMove(MoveType.Fighter,     30, 1.60,  -33)
  case Brine          extends ChargeMove(MoveType.Water,       25, 2.40,  -25)
  case BubbleBeam     extends ChargeMove(MoveType.Water,       30, 2.90,  -25)
  case BugBuzz        extends ChargeMove(MoveType.Bug,         75, 4.25,  -50)
  case Bulldoze       extends ChargeMove(MoveType.Ground,      35, 3.40,  -25)
  case CrossChop      extends ChargeMove(MoveType.Fighter,     60, 2.00, -100)
  case CrossPoison    extends ChargeMove(MoveType.Poison,      25, 1.50,  -25)
  case DarkPulse      extends ChargeMove(MoveType.Dark,        45, 3.50,  -33)
  case DazzlingGleam  extends ChargeMove(MoveType.Fairy,       55, 4.20,  -33)
  case Dig            extends ChargeMove(MoveType.Ground,      70, 5.80,  -33)
  case DisarmingVoice extends ChargeMove(MoveType.Fairy,       25, 3.90,  -20)
  case Discharge      extends ChargeMove(MoveType.Electric,    35, 2.50,  -33)
  case DragonClaw     extends ChargeMove(MoveType.Dragon,      35, 1.60,  -50)
  case DragonPulse    extends ChargeMove(MoveType.Dragon,      65, 3.60,  -50)
  case DrainingKiss   extends ChargeMove(MoveType.Fairy,       25, 2.80,  -20)
  case DrillPeck      extends ChargeMove(MoveType.Flying,      40, 2.70,  -33)
  case DrillRun       extends ChargeMove(MoveType.Ground,      50, 3.40,  -33)
  case Earthquake     extends ChargeMove(MoveType.Ground,     100, 4.20, -100)
  case FireBlast      extends ChargeMove(MoveType.Fire,       100, 4.10, -100)
  case FirePunch      extends ChargeMove(MoveType.Fire,        40, 2.80,  -33)
  case FlameBurst     extends ChargeMove(MoveType.Fire,        30, 2.10,  -25)
  case FlameCharge    extends ChargeMove(MoveType.Fire,        25, 3.10,  -20)
  case FlameWheel     extends ChargeMove(MoveType.Fire,        40, 4.60,  -25)
  case Flamethrower   extends ChargeMove(MoveType.Fire,        55, 2.90,  -50)
  case FlashCannon    extends ChargeMove(MoveType.Steel,       60, 3.90,  -33)
  case GunkShot       extends ChargeMove(MoveType.Poison,      65, 3.00, -100)
  case HeatWave       extends ChargeMove(MoveType.Fire,        80, 3.80, -100)
  case HornAttack     extends ChargeMove(MoveType.Normal,      25, 2.20,  -25)
  case Hurricane      extends ChargeMove(MoveType.Flying,      80, 3.20, -100)
  case HydroPump      extends ChargeMove(MoveType.Water,       90, 3.80, -100)
  case HyperBeam      extends ChargeMove(MoveType.Normal,     120, 5.00, -100)
  case HyperFang      extends ChargeMove(MoveType.Normal,      35, 2.10,  -33)
  case IceBeam        extends ChargeMove(MoveType.Ice,         65, 3.65,  -50)
  case IcePunch       extends ChargeMove(MoveType.Ice,         45, 3.50,  -33)
  case IcyWind        extends ChargeMove(MoveType.Ice,         25, 3.80,  -20)
  case IronHead       extends ChargeMove(MoveType.Steel,       30, 2.00,  -33)
  case LeafBlade      extends ChargeMove(MoveType.Grass,       55, 2.80,  -50)
  case LowSweep       extends ChargeMove(MoveType.Fighter,     30, 2.25,  -25)
  case MagnetBomb     extends ChargeMove(MoveType.Steel,       30, 2.80,  -25)
  case Megahorn       extends ChargeMove(MoveType.Bug,         80, 3.20, -100)
  case Moonblast      extends ChargeMove(MoveType.Fairy,       85, 4.10, -100)
  case MudBomb        extends ChargeMove(MoveType.Ground,      30, 2.60,  -25)
  case NightSlash     extends ChargeMove(MoveType.Dark,        30, 2.70,  -25)
  case OminousWind    extends ChargeMove(MoveType.Ghost,       30, 3.10,  -25)
  case PetalBlizzard  extends ChargeMove(MoveType.Grass,       65, 3.20,  -50)
  case PlayRough      extends ChargeMove(MoveType.Fairy,       55, 2.90,  -50)
  case PoisonFang     extends ChargeMove(MoveType.Poison,      25,  2.4,  -20)
  case PowerGem       extends ChargeMove(MoveType.Rock,        40, 2.90,  -33)
  case PowerWhip      extends ChargeMove(MoveType.Grass,       70, 2.80, -100)
  case Psybeam        extends ChargeMove(MoveType.Psychic,     40, 3.80,  -25)
  case Psychic        extends ChargeMove(MoveType.Psychic,     55, 2.80,  -50)
  case Psyshock       extends ChargeMove(MoveType.Psychic,     40, 2.70,  -33)
  case RockSlide      extends ChargeMove(MoveType.Rock,        50, 3.20,  -33)
  case RockTomb       extends ChargeMove(MoveType.Rock,        30, 3.40,  -25)
  case Scald          extends ChargeMove(MoveType.Water,       55, 4.00,  -33)
  case SeedBomb       extends ChargeMove(MoveType.Grass,       40, 2.40,  -33)
  case ShadowBall     extends ChargeMove(MoveType.Ghost,       45, 3.08,  -33)
  case SignalBeam     extends ChargeMove(MoveType.Bug,         45, 3.10,  -33)
  case Sludge         extends ChargeMove(MoveType.Poison,      30, 2.60,  -25)
  case SludgeBomb     extends ChargeMove(MoveType.Poison,      55, 2.60,  -50)
  case SludgeWave     extends ChargeMove(MoveType.Poison,      70, 3.40, -100)
  case SolarBeam      extends ChargeMove(MoveType.Grass,      120, 4.90, -100)
  case Stomp          extends ChargeMove(MoveType.Normal,      30, 2.10,  -25)
  case StoneEdge      extends ChargeMove(MoveType.Rock,        80, 3.10, -100)
  case Struggle       extends ChargeMove(MoveType.Bug,         15, 1.70,  -20)
  case Submission     extends ChargeMove(MoveType.Fighter,     30, 2.19,  -33)
  case Swift          extends ChargeMove(MoveType.Normal,      30, 3.99,  -25)
  case Thunder        extends ChargeMove(MoveType.Electric,   100, 4.30, -100)
  case ThunderPunch   extends ChargeMove(MoveType.Electric,    40, 2.40,  -33)
  case Thunderbolt    extends ChargeMove(MoveType.Electric,    55, 2.79,  -50)
  case Twister        extends ChargeMove(MoveType.Dragon,      25, 2.79,  -20)
  case ViceGrip       extends ChargeMove(MoveType.Normal,      25, 2.19,  -20)
  case WaterPulse     extends ChargeMove(MoveType.Water,       35, 3.39,  -25)
  case Wrap           extends ChargeMove(MoveType.Normal,      25, 4.00,  -20)
  case XScissor       extends ChargeMove(MoveType.Bug,         35, 2.19,  -33)

enum Pokemon(
  val pTypes: (PokeType, PokeType),
  val cpStep: Double,
  val cpMax: Int,
  val fastL: List[FastMove],
  val chargeL: List[ChargeMove],
):
  case Butterfree extends Pokemon(PokeType.Bug      -> PokeType.Flying,   19.1, 1454, List(FastMove.BugBite, FastMove.Confusion), List(ChargeMove.BugBuzz, ChargeMove.Psychic,  ChargeMove.SignalBeam))
  case Beedrill   extends Pokemon(PokeType.Bug      -> PokeType.Poison,   18.9, 1439, List(FastMove.BugBite, FastMove.PoisonJab), List(ChargeMove.AerialAce, ChargeMove.SludgeBomb, ChargeMove.XScissor))
  case Parasect   extends Pokemon(PokeType.Bug      -> PokeType.Grass,    23.2, 1747, List(FastMove.BugBite, FastMove.FuryCutter), List(ChargeMove.CrossPoison, ChargeMove.SolarBeam, ChargeMove.XScissor))
  case Venomoth   extends Pokemon(PokeType.Bug      -> PokeType.Poison,   25.2, 1890, List(FastMove.BugBite, FastMove.Confusion), List(ChargeMove.BugBuzz, ChargeMove.PoisonFang, ChargeMove.Psychic))
  case Scyther    extends Pokemon(PokeType.Bug      -> PokeType.Flying,   27.7, 2073, List(FastMove.FuryCutter, FastMove.SteelWing), List(ChargeMove.BugBuzz, ChargeMove.NightSlash, ChargeMove.XScissor))
  case Pinsir     extends Pokemon(PokeType.Bug      -> PokeType.None,     28.4, 2121, List(FastMove.FuryCutter, FastMove.RockSmash), List(ChargeMove.Submission, ChargeMove.ViceGrip, ChargeMove.XScissor))
  case Dragonite  extends Pokemon(PokeType.Dragon   -> PokeType.Flying,   47.7, 3500, List(FastMove.DragonBreath, FastMove.SteelWing), List(ChargeMove.DragonClaw, ChargeMove.DragonPulse, ChargeMove.HyperBeam))
  case Raichu     extends Pokemon(PokeType.Electric -> PokeType.None,     27.1, 2028, List(FastMove.Spark, FastMove.ThunderShock), List(ChargeMove.BrickBreak, ChargeMove.Thunder, ChargeMove.ThunderPunch))
  case Magneton   extends Pokemon(PokeType.Electric -> PokeType.Steel,    25.0, 1879, List(FastMove.Spark, FastMove.ThunderShock), List(ChargeMove.Discharge, ChargeMove.FlashCannon, ChargeMove.MagnetBomb))
  case Electrode  extends Pokemon(PokeType.Electric -> PokeType.None,     21.8, 1646, List(FastMove.Spark, FastMove.Tackle), List(ChargeMove.Discharge, ChargeMove.HyperBeam, ChargeMove.Thunderbolt))
  case Electabuzz extends Pokemon(PokeType.Electric -> PokeType.None,     28.3, 2119, List(FastMove.LowKick, FastMove.ThunderShock), List(ChargeMove.Thunder, ChargeMove.Thunderbolt, ChargeMove.ThunderPunch))
  case Jolteon    extends Pokemon(PokeType.Electric -> PokeType.None,     28.6, 2140, List(FastMove.ThunderShock, FastMove.ThunderShock), List(ChargeMove.Discharge, ChargeMove.Thunder, ChargeMove.Thunderbolt))
  case Clefable   extends Pokemon(PokeType.Fairy    -> PokeType.None,     32.3, 2397, List(FastMove.Pound, FastMove.ZenHeadbutt), List(ChargeMove.DazzlingGleam, ChargeMove.Moonblast, ChargeMove.Psychic))
  case Primeape   extends Pokemon(PokeType.Fighter  -> PokeType.None,     24.8, 1864, List(FastMove.KarateChop, FastMove.LowKick), List(ChargeMove.CrossChop, ChargeMove.LowSweep, ChargeMove.NightSlash))
  case Machamp    extends Pokemon(PokeType.Fighter  -> PokeType.None,     35.0, 2594, List(FastMove.BulletPunch, FastMove.KarateChop), List(ChargeMove.CrossChop, ChargeMove.StoneEdge, ChargeMove.Submission))
  case Hitmonlee  extends Pokemon(PokeType.Fighter  -> PokeType.None,     19.6, 1492, List(FastMove.LowKick, FastMove.RockSmash), List(ChargeMove.BrickBreak, ChargeMove.LowSweep, ChargeMove.StoneEdge))
  case Hitmonchan extends Pokemon(PokeType.Fighter  -> PokeType.None,     19.9, 1516, List(FastMove.BulletPunch, FastMove.RockSmash), List(ChargeMove.FirePunch, ChargeMove.IcePunch, ChargeMove.ThunderPunch, ChargeMove.BrickBreak))
  case Charizard  extends Pokemon(PokeType.Fire     -> PokeType.Flying,   35.1, 2602, List(FastMove.Ember, FastMove.WingAttack), List(ChargeMove.DragonClaw, ChargeMove.FireBlast, ChargeMove.Flamethrower))
  case Ninetails  extends Pokemon(PokeType.Fire     -> PokeType.None,     29.3, 2188, List(FastMove.Ember, FastMove.FeintAttack), List(ChargeMove.FireBlast, ChargeMove.Flamethrower, ChargeMove.HeatWave))
  case Arcanine   extends Pokemon(PokeType.Fire     -> PokeType.None,     40.5, 2983, List(FastMove.Bite, FastMove.FireFang), List(ChargeMove.Bulldoze, ChargeMove.FireBlast, ChargeMove.Flamethrower))
  case Rapidash   extends Pokemon(PokeType.Fire     -> PokeType.None,     29.5, 2199, List(FastMove.Ember, FastMove.LowKick), List(ChargeMove.DrillRun, ChargeMove.FireBlast, ChargeMove.HeatWave))
  case Magmar     extends Pokemon(PokeType.Fire     -> PokeType.None,     30.4, 2265, List(FastMove.Ember, FastMove.KarateChop), List(ChargeMove.FireBlast, ChargeMove.FirePunch, ChargeMove.Flamethrower))
  case Flareon    extends Pokemon(PokeType.Fire     -> PokeType.None,     35.6, 2643, List(FastMove.Ember), List(ChargeMove.HeatWave, ChargeMove.FireBlast, ChargeMove.Flamethrower))
  case Gengar     extends Pokemon(PokeType.Ghost    -> PokeType.Poison,   27.8, 2078, List(FastMove.ShadowClaw, FastMove.SuckerPunch), List(ChargeMove.DarkPulse, ChargeMove.ShadowBall, ChargeMove.SludgeBomb))
  case Venusaur   extends Pokemon(PokeType.Grass    -> PokeType.Poison,   34.8, 2580, List(FastMove.RazorLeaf, FastMove.VineWhip), List(ChargeMove.PetalBlizzard, ChargeMove.SludgeBomb, ChargeMove.SolarBeam))
  case Vileplume  extends Pokemon(PokeType.Grass    -> PokeType.Poison,   33.6, 2492, List(FastMove.Acid, FastMove.RazorLeaf), List(ChargeMove.Moonblast, ChargeMove.PetalBlizzard, ChargeMove.SolarBeam))
  case Victreebel extends Pokemon(PokeType.Grass    -> PokeType.Poison,   34.1, 2530, List(FastMove.Acid, FastMove.RazorLeaf), List(ChargeMove.LeafBlade, ChargeMove.SludgeBomb, ChargeMove.SolarBeam))
  case Exeggutor  extends Pokemon(PokeType.Grass    -> PokeType.Psychic,  40.1, 2955, List(FastMove.Confusion, FastMove.ZenHeadbutt), List(ChargeMove.Psychic, ChargeMove.SeedBomb, ChargeMove.SolarBeam))
  case Tangela    extends Pokemon(PokeType.Grass    -> PokeType.None,     23.1, 1739, List(FastMove.VineWhip), List(ChargeMove.PowerWhip, ChargeMove.SludgeBomb, ChargeMove.SolarBeam))
  case Jynx       extends Pokemon(PokeType.Ice      -> PokeType.Psychic,  22.8, 1716, List(FastMove.FrostBreath, FastMove.Pound), List(ChargeMove.DrainingKiss, ChargeMove.IcePunch, ChargeMove.Psyshock))
  case Pidgeot    extends Pokemon(PokeType.Normal   -> PokeType.Flying,   28.0, 2091, List(FastMove.SteelWing, FastMove.WingAttack), List(ChargeMove.AerialAce, ChargeMove.AirCutter, ChargeMove.Hurricane))
  case Raticate   extends Pokemon(PokeType.Normal   -> PokeType.None,     19.0, 1444, List(FastMove.Bite, FastMove.QuickAttack), List(ChargeMove.Dig, ChargeMove.HyperBeam, ChargeMove.HyperFang))
  case Fearow     extends Pokemon(PokeType.Normal   -> PokeType.Flying,   23.2, 1746, List(FastMove.Peck, FastMove.SteelWing), List(ChargeMove.AerialAce, ChargeMove.DrillRun, ChargeMove.Twister))
  case Wigglytuff extends Pokemon(PokeType.Normal   -> PokeType.Fairy,    29.1, 2177, List(FastMove.FeintAttack, FastMove.Pound), List(ChargeMove.DazzlingGleam, ChargeMove.HyperBeam, ChargeMove.PlayRough))
  case Persian    extends Pokemon(PokeType.Normal   -> PokeType.None,     21.6, 1631, List(FastMove.FeintAttack, FastMove.Scratch), List(ChargeMove.NightSlash, ChargeMove.PlayRough, ChargeMove.PowerGem))
  case Dodrio     extends Pokemon(PokeType.Normal   -> PokeType.Flying,   24.4, 1836, List(FastMove.FeintAttack, FastMove.SteelWing), List(ChargeMove.AerialAce, ChargeMove.AirCutter, ChargeMove.DrillPeck))
  case Lickitung  extends Pokemon(PokeType.Normal   -> PokeType.None,     21.5, 1626, List(FastMove.Lick, FastMove.ZenHeadbutt), List(ChargeMove.HyperBeam, ChargeMove.PowerWhip, ChargeMove.Stomp))
  case Porygon    extends Pokemon(PokeType.Normal   -> PokeType.None,     22.4, 1691, List(FastMove.Tackle, FastMove.ZenHeadbutt), List(ChargeMove.Discharge, ChargeMove.Psybeam, ChargeMove.SignalBeam))
  case Snorlax    extends Pokemon(PokeType.Normal   -> PokeType.None,     42.2, 3112, List(FastMove.Lick, FastMove.ZenHeadbutt), List(ChargeMove.BodySlam, ChargeMove.Earthquake, ChargeMove.HyperBeam))
  case Arbok      extends Pokemon(PokeType.Poison   -> PokeType.None,     23.5, 1767, List(FastMove.Acid, FastMove.Bite), List(ChargeMove.DarkPulse, ChargeMove.GunkShot, ChargeMove.SludgeWave))
  case Nidoqueen  extends Pokemon(PokeType.Poison   -> PokeType.Ground,   33.5, 2485, List(FastMove.Bite, FastMove.PoisonJab), List(ChargeMove.Earthquake, ChargeMove.SludgeWave, ChargeMove.StoneEdge))
  case Nidoking   extends Pokemon(PokeType.Poison   -> PokeType.Ground,   33.3, 2475, List(FastMove.FuryCutter, FastMove.PoisonJab), List(ChargeMove.Earthquake, ChargeMove.Megahorn, ChargeMove.SludgeWave))
  case Golbat     extends Pokemon(PokeType.Poison   -> PokeType.Flying,   25.6, 1921, List(FastMove.Bite, FastMove.WingAttack), List(ChargeMove.AirCutter, ChargeMove.OminousWind, ChargeMove.PoisonFang))
  case Muk        extends Pokemon(PokeType.Poison   -> PokeType.None,     35.1, 2602, List(FastMove.Lick, FastMove.PoisonJab), List(ChargeMove.DarkPulse, ChargeMove.GunkShot, ChargeMove.SludgeWave))
  case Weezing    extends Pokemon(PokeType.Poison   -> PokeType.None,     30.2, 2250, List(FastMove.Tackle), List(ChargeMove.DarkPulse, ChargeMove.ShadowBall, ChargeMove.SludgeBomb))
  case Alakazam   extends Pokemon(PokeType.Psychic  -> PokeType.None,     24.1, 1813, List(FastMove.Confusion, FastMove.PsychoCut), List(ChargeMove.DazzlingGleam, ChargeMove.Psychic, ChargeMove.ShadowBall))
  case Hypno      extends Pokemon(PokeType.Psychic  -> PokeType.None,     29.3, 2184, List(FastMove.Confusion, FastMove.ZenHeadbutt), List(ChargeMove.Psychic, ChargeMove.Psyshock, ChargeMove.ShadowBall))
  case MrMime     extends Pokemon(PokeType.Psychic  -> PokeType.Fairy,    19.6, 1494, List(FastMove.Confusion, FastMove.ZenHeadbutt), List(ChargeMove.Psybeam, ChargeMove.Psychic, ChargeMove.ShadowBall))
  case Sandslash  extends Pokemon(PokeType.Ground   -> PokeType.None,     24.1, 1810, List(FastMove.MetalClaw, FastMove.MudShot), List(ChargeMove.Bulldoze, ChargeMove.Earthquake, ChargeMove.RockTomb))
  case Digtrio    extends Pokemon(PokeType.Ground   -> PokeType.None,     15.1, 1168, List(FastMove.MudSlap, FastMove.SuckerPunch), List(ChargeMove.Earthquake, ChargeMove.MudBomb, ChargeMove.StoneEdge))
  case Marowak    extends Pokemon(PokeType.Ground   -> PokeType.None,     21.9, 1656, List(FastMove.MudSlap, FastMove.RockSmash), List(ChargeMove.BoneClub, ChargeMove.Dig, ChargeMove.Earthquake))
  case Rhydon     extends Pokemon(PokeType.Ground   -> PokeType.Rock,     30.1, 2243, List(FastMove.MudSlap, FastMove.RockSmash), List(ChargeMove.Earthquake, ChargeMove.Megahorn, ChargeMove.StoneEdge))
  case Golem      extends Pokemon(PokeType.Rock     -> PokeType.Ground,   30.9, 2303, List(FastMove.MudSlap, FastMove.RockThrow), List(ChargeMove.AncientPower, ChargeMove.Earthquake, ChargeMove.StoneEdge))
  case Onix       extends Pokemon(PokeType.Rock     -> PokeType.Ground,   10.9,  857, List(FastMove.RockThrow, FastMove.Tackle), List(ChargeMove.IronHead, ChargeMove.RockSlide, ChargeMove.StoneEdge))
  case Omastar    extends Pokemon(PokeType.Rock     -> PokeType.Water,    30.0, 2233, List(FastMove.MudShot, FastMove.WaterGun), List(ChargeMove.AncientPower, ChargeMove.HydroPump, ChargeMove.RockSlide))
  case Kabutops   extends Pokemon(PokeType.Rock     -> PokeType.Water,    28.5, 2130, List(FastMove.FuryCutter, FastMove.MudShot), List(ChargeMove.AncientPower, ChargeMove.StoneEdge, ChargeMove.WaterPulse))
  case Aerodactyl extends Pokemon(PokeType.Rock     -> PokeType.Flying,   29.0, 2165, List(FastMove.Bite, FastMove.SteelWing), List(ChargeMove.AncientPower, ChargeMove.HyperBeam, ChargeMove.IronHead))
  case Blastoise  extends Pokemon(PokeType.Water    -> PokeType.None,     34.3, 2542, List(FastMove.Bite, FastMove.WaterGun), List(ChargeMove.FlashCannon, ChargeMove.HydroPump, ChargeMove.IceBeam))
  case Golduck    extends Pokemon(PokeType.Water    -> PokeType.None,     32.1, 2386, List(FastMove.WaterGun, FastMove.Confusion), List(ChargeMove.HydroPump, ChargeMove.IceBeam, ChargeMove.Psychic))
  case Poliwrath  extends Pokemon(PokeType.Water    -> PokeType.Fighter,  33.8, 2505, List(FastMove.Bubble, FastMove.MudShot), List(ChargeMove.HydroPump, ChargeMove.IcePunch, ChargeMove.Submission))
  case Tentacruel extends Pokemon(PokeType.Water    -> PokeType.Poison,   29.8, 2220, List(FastMove.Acid, FastMove.PoisonJab), List(ChargeMove.Blizzard, ChargeMove.HydroPump, ChargeMove.SludgeWave))
  case Slobro     extends Pokemon(PokeType.Water    -> PokeType.Psychic,  35.1, 2597, List(FastMove.Confusion, FastMove.WaterGun), List(ChargeMove.IceBeam, ChargeMove.Psychic, ChargeMove.WaterPulse))
  case Dewgong    extends Pokemon(PokeType.Water    -> PokeType.Ice,      28.7, 2145, List(FastMove.FrostBreath, FastMove.IceShard), List(ChargeMove.AquaJet, ChargeMove.Blizzard, ChargeMove.IcyWind))
  case Cloyster   extends Pokemon(PokeType.Water    -> PokeType.Ice,      27.4, 2052, List(FastMove.FrostBreath, FastMove.IceShard), List(ChargeMove.Blizzard, ChargeMove.HydroPump, ChargeMove.IcyWind))
  case Kingler    extends Pokemon(PokeType.Water    -> PokeType.None,     24.2, 1823, List(FastMove.MetalClaw, FastMove.MudShot), List(ChargeMove.ViceGrip, ChargeMove.WaterPulse, ChargeMove.XScissor))
  case Seadra     extends Pokemon(PokeType.Water    -> PokeType.None,     22.7, 1713, List(FastMove.DragonBreath, FastMove.WaterGun), List(ChargeMove.Blizzard, ChargeMove.DragonPulse, ChargeMove.HydroPump))
  case Seaking    extends Pokemon(PokeType.Water    -> PokeType.None,     27.3, 2043, List(FastMove.Peck, FastMove.PoisonJab), List(ChargeMove.DrillRun, ChargeMove.IcyWind, ChargeMove.Megahorn))
  case Starmie    extends Pokemon(PokeType.Water    -> PokeType.Psychic,  29.2, 2182, List(FastMove.Tackle, FastMove.WaterGun), List(ChargeMove.HydroPump, ChargeMove.PowerGem, ChargeMove.Psychic, ChargeMove.Psybeam))
  case Gyarados   extends Pokemon(PokeType.Water    -> PokeType.Flying,   36.4, 2688, List(FastMove.Bite), List(ChargeMove.DragonPulse, ChargeMove.HydroPump, ChargeMove.Twister))
  case Lapras     extends Pokemon(PokeType.Water    -> PokeType.Ice,      40.4, 2980, List(FastMove.FrostBreath, FastMove.IceShard), List(ChargeMove.Blizzard, ChargeMove.DragonPulse, ChargeMove.IceBeam))
  case Vaporeon   extends Pokemon(PokeType.Water    -> PokeType.None,     38.1, 2816, List(FastMove.WaterGun), List(ChargeMove.AquaTail, ChargeMove.HydroPump, ChargeMove.WaterPulse))

